version: '3'

services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: 'mongodb'
    hostname: 'mongo'
    ports:
      - "27017:27017"
    restart: always