/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBarDemo: typeof import('./src/components/AppBarDemo.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavDrawerPurpleDemo: typeof import('./src/components/NavDrawerPurpleDemo.vue')['default']
    Nested: typeof import('./src/components/infra/nested.vue')['default']
    Rank: typeof import('./src/components/Rank.vue')['default']
    RawDisplayer: typeof import('./src/components/infra/raw-displayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sort: typeof import('./src/components/Sort.vue')['default']
  }
}
